import {readable, writable} from 'svelte/store';

export const menusSetup = readable([
    {
        _id:'studiesMenu',
        componentType: 'PullDownMenu',
        paneIntWidth: 221,
        isChecked: false,
        isActive: false,
        components: [
            {componentId: 'new', componentType: 'MenuPushButton'},
            {componentId: 'open', componentType: 'MenuPushButton'},
            {componentType: 'DividerHorizontal', componentDevice: 'laptop tablet'},
            {componentId: 'newInner', componentType: 'MenuPushButton'},
            {componentId: 'newOuter', componentType: 'MenuPushButton'},
            {componentType: 'DividerHorizontal', componentDevice: 'laptop tablet'},
            {componentId: 'newCompare', componentType: 'MenuPushButton'},
        ],
    },
    {
        _id: 'zoomMenu',
        componentType: 'PullDownMenu',
        paneIntWidth: 97,
        isChecked: true,
        isActive: false,
        components: [
            {componentId: '25', componentType: 'MenuPushButton'},
            {componentId: '50', componentType: 'MenuPushButton'},
            {componentId: '75', componentType: 'MenuPushButton'},
            {componentId: '100', componentType: 'MenuPushButton'},
            {componentId: '125', componentType: 'MenuPushButton'},
            {componentId: '150', componentType: 'MenuPushButton'},
            {componentId: '200', componentType: 'MenuPushButton'},
            {componentId: '300', componentType: 'MenuPushButton'},
            {componentId: '400', componentType: 'MenuPushButton'},
            {componentType: 'DividerHorizontal', componentDevice: 'laptop tablet'},
            {componentId: 'fitWidth', componentType: 'MenuPushButton'},
            {componentId: 'fitPage', componentType: 'MenuPushButton'},
        ],
    },
    {
        _id: 'outlineMenu',
        componentType: 'PullDownMenu',
        paneIntWidth: 160,
        isChecked: false,
        isActive: false,
        components: [
            {componentId: 'section', componentType: 'MenuPushButton'},
            {componentId: 'column', componentType: 'MenuPushButton'},
            {componentId: 'group', componentType: 'MenuPushButton'},
            {componentType: 'DividerHorizontal', componentDevice: 'laptop tablet'},
            {componentId: 'unpin', componentType: 'MenuPushButton'},
            {componentId: 'pin', componentType: 'MenuPushButton'},
        ],
    },
    {
        _id: 'textMenu',
        componentType: 'PullDownMenu',
        paneIntWidth: 185,
        isChecked: false,
        isActive: false,
        components: [
            {componentId: 'highlight', componentType: 'MenuPushButton'},
            {componentType: 'DividerHorizontal', componentDevice: 'laptop tablet'},
            {componentId: 'split', componentType: 'MenuPushButton'},
            {componentId: 'join', componentType: 'MenuPushButton'},
            {componentType: 'DividerHorizontal', componentDevice: 'laptop tablet'},
            {componentId: 'moveUp', componentType: 'MenuPushButton'},
            {componentId: 'moveDown', componentType: 'MenuPushButton'},  
        ],
    },
    {
        _id: 'literaryMenu',
        componentType: 'PullDownMenu',
        paneIntWidth: 199,
        isChecked: false,
        isActive: false,
        components: [
            {componentId: 'chiasim', componentType: 'MenuPushButton'},
            {componentId: 'paralellism', componentType: 'MenuPushButton'},
            {componentId: 'repetition', componentType: 'MenuPushButton'},
            {componentId: 'intensification', componentType: 'MenuPushButton'},
        ],
    },
    {
        _id: 'optionsMenu',
        componentType: 'PullDownMenu',
        paneIntWidth: 230,
        isChecked: false,
        isActive: false,
        components: [
            {componentId: 'references', componentType: 'MenuPushButton'},
            {componentId: 'footnotes', componentType: 'MenuPushButton'},
            {componentId: 'verses', componentType: 'MenuPushButton'},
            {componentId: 'headings', componentType: 'MenuPushButton'},
        ],
    },
    {
        _id: 'colorMenu',
        componentType: 'PullDownMenu',
        paneIntWidth: 87,
        isChecked: false,
        isActive: false,
        components: [
            {componentId: 'red', componentType: 'MenuPushButton'},
            {componentId: 'orange', componentType: 'MenuPushButton'},
            {componentId: 'yellow', componentType: 'MenuPushButton'},
            {componentId: 'green', componentType: 'MenuPushButton'},
            {componentId: 'aqua', componentType: 'MenuPushButton'},
            {componentId: 'blue', componentType: 'MenuPushButton'},
            {componentId: 'purple', componentType: 'MenuPushButton'},
            {componentId: 'pink', componentType: 'MenuPushButton'},
        ],
    },
    {
        _id: 'settingsMenu',
        componentType: 'PullDownMenu',
        paneIntWidth: 164,
        isChecked: false,
        isActive: false,
        components: [
            {componentId: 'account', componentType: 'MenuPushButton'},
            {componentId: 'toolbar', componentType: 'MenuPushButton'},
            {componentId: 'help', componentType: 'MenuPushButton'},
            {componentType: 'DividerHorizontal', componentDevice: 'laptop tablet'},
            {componentId: 'signout', componentType: 'MenuPushButton'},      
        ],
    },
]);

export const menusState = writable({});