<script>
    import Menu from "../../elements/Menu.svelte";
    import Button from "../../elements/Button.svelte";
</script>

<Menu _id='menuColor'>
    <Button 
        color="system-menu"
        icon="circle"
        iconColor="red"
        iconStrokeColor="red"
        label="red"
        isDisabled
        labelIsLeft
    />
    <Button 
        color="system-menu"
        icon="circle"
        iconColor="orange"
        iconStrokeColor="orange"
        label="Orange"
        isDisabled
        labelIsLeft
    />
    <Button 
        color="system-menu"
        icon="circle"
        iconColor="yellow"
        iconStrokeColor="yellow"
        label="Yellow"
        isDisabled
        labelIsLeft
    />
    <Button 
        color="system-menu"
        icon="circle"
        iconColor="green"
        iconStrokeColor="green"
        label="Green"
        isDisabled
        labelIsLeft
    />
    <Button 
        color="system-menu"
        icon="circle"
        iconColor="aqua"
        iconStrokeColor="aqua"
        label="Aqua"
        isDisabled
        labelIsLeft
    />
    <Button 
        color="system-menu"
        icon="circle"
        iconColor="blue"
        iconStrokeColor="blue"
        label="Blue"
        isDisabled
        labelIsLeft
    />
    <Button 
        color="system-menu"
        icon="circle"
        iconColor="purple"
        iconStrokeColor="purple"
        label="Purple"
        isDisabled
        labelIsLeft
    />
    <Button 
        color="system-menu"
        icon="circle"
        iconColor="pink"
        iconStrokeColor="pink"
        label="Pink"
        isDisabled
        labelIsLeft
    />
</Menu>